### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by luugh** [bagetter/BaGetter#27] opened 2023-12-28 07:23 UTC
### Describe the bug
When I was building the image, an error occurred and I don't know where to adjust it

### Screenshots

![image](https://github.com/bagetter/BaGetter/assets/9065694/c0058d9c-c6b5-4483-a733-8b0c79fe5f18)

**Comment by seriouz** [comment] 2023-12-30 20:11
@luugh I can't reproduce the problem and the Dockerfile works fine on the GitHub Runner too.
May it be that you are behind a proxy or something like that?

**Comment by daghsentinel** [comment] 2024-01-05 07:25
@luugh  - error code 137 might indicate out of memory error

**Comment by Regenhardt** [comment] 2024-01-09 13:00
@luugh please provide more details. 

How much RAM does the machine you run this build on have?   
When running it, how much of the RAM is being used?  
Did you set any app settings in the appsettings file, the Dockerfile, or as environment variables on the environment you ran this build in?

**Comment by Leonid-Vizel** [comment] 2024-02-09 09:05
@luugh, check [this issue](https://github.com/PowerShell/PowerShell/issues/17624) from [PowerShell](https://github.com/PowerShell/PowerShell) repository

I guess the issue is not related to BaGetter

**Comment by daghsentinel** [comment] 2024-02-09 09:10
Closing issue due to no new information

**Closed by daghsentinel** 2024-02-09 09:10 UTC
Labels: wontfix
